title: "Your Blog Title"  # Add your site title here
description: "A description of your site"  # Optional, helps with SEO

# GitHub Pages settings
baseurl: "/heydeep-blog"  # Ensure this matches the repository name
url: "https://proffdeep.github.io"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
